### ISSUE TITLE
Invisible links in navigation (pipelines)

### ISSUE THREAD

**Issue by eliasnorrby** [tektoncd/website#271]
# Expected Behavior
All documents should have a visible link in the sidebar.

# Actual Behavior
Link text is missing for a number of documents.

# Steps to Reproduce the Problem

1. Visit https://tekton.dev/docs
2. Expand Tasks and Pipelines in the sidebar
3. Hover over the blank space below "Deprecations"

# Image
<img width="1428" alt="invisible_links" src="https://user-images.githubusercontent.com/11960052/118637594-46953500-b7d6-11eb-9e17-5c97e5ff1107.png">

# Cause
These files under `tektoncd/pipelines/docs` are missing the frontmatter block (and thus the `linkTitle` field):
- [enabling-ha.md](https://raw.githubusercontent.com/tektoncd/pipeline/main/docs/enabling-ha.md)
- [migrating-v1alpha1-to-v1beta1.md](https://raw.githubusercontent.com/tektoncd/pipeline/main/docs/migrating-v1alpha1-to-v1beta1.md)
- [install.md](https://raw.githubusercontent.com/tektoncd/pipeline/main/docs/install.md)
- [tekton-controller-performance-configuration.md](https://raw.githubusercontent.com/tektoncd/pipeline/main/docs/tekton-controller-performance-configuration.md)

**Comment by afrittoli** [comment]
Nice catch, thank you!
It feels like this should be fixed on pipeline side? 
Until then we could either exclude them via the config or specify the link title on website side.

**Comment by eliasnorrby** [comment]
Yeah, this is easy enough to resolve, but relates to #270 in that the fix must be merged to all previous releases. Do you think the strategy of using branch refs in the sync config is appropriate for this?

**Comment by afrittoli** [comment]
I think that would be a nice solution - however the `sync` tool right now looks for `tags` and local refs only - we would need to extend it to work with remote branches too.

**Comment by afrittoli** [comment]
Heh, in fact specifying the branch in the config as `origin/<branch-name>` already works with the existing code - but I guess it would be nicer to be able to configure the branch name alone.

**Comment by eliasnorrby** [comment]
That's true, but for [that part](https://github.com/tektoncd/website/blob/e8b68d6b5eb23675decf98c2d6e00e4187fb3947/sync/sync.py#L108-L128) of `sync.py`, a ref like `origin/release-v0.12.1` should work.  tried using a remote branch ref [here](https://github.com/tektoncd/website/pull/270#discussion_r634255064), and it seems to work.

**Comment by eliasnorrby** [comment]
Haha, you're one step ahead of me. Yes, that would be nice.

**Comment by afrittoli** [comment]
Ah, nice. I think we could start using the ref like you did in the triggers patch.
If you'd like, you could also add support for specifying the ref without the `origin/` part, as a follow-up.
Thank for looking into this, it's much appreciated!

**Comment by eliasnorrby** [comment]
Cool, I'll take a look! That means I'll
- open a PR for each (relevant) release branch within `triggers` to update frontmatter, specifically `linkTitles`, for navigation to make sense
- open a PR for each (relevant) release branch within `pipelines` to add the missing frontmatter to fix invisible links
- open one or more PRs in `website` to use branch references in the sync config (one of which will be #270)

I'll need help with making sure there is a release branch available for every release that needs to be patched. `pipelines@v0.22.0` for example has no matching release branch. I can detail which branches need to be pushed in the `website` PRs, but I think it'll be:
- triggers: every release from v0.10.1 and up
- pipelines: every release from v0.14.3 and up

**Comment by afrittoli** [comment]
Thanks! 
I can create the branches. I would start from `main` and work your way backwards, but I would say only for releases that are published on the website.

**Comment by afrittoli** [comment]
@eliasnorrby please let me know if there are branched that you need me to create for pipeline and/or triggers 🙏 
Thank you again for driving this forward!!!

**Comment by eliasnorrby** [comment]
Okay, here's the list of `pipeline` releases available on the website in need of patching: 

- [ ] `release-v0.24.x` no branch available
- [ ] `release-v0.23.x` no branch available
- [ ] `release-v0.22.x` no branch available
- [ ] `release-v0.21.x` no branch available
- [ ] `release-v0.20.x` OPEN tektoncd/pipeline#3980
- [ ] `release-v0.19.x` no branch available
- [ ] `release-v0.18.x` OPEN tektoncd/pipeline#3981
- [ ] `release-v0.17.x` OPEN tektoncd/pipeline#3982
- [ ] `release-v0.16.x` OPEN tektoncd/pipeline#3983
- [ ] `release-v0.15.x` OPEN tektoncd/pipeline#3984
- [ ] `release-v0.14.x` OPEN tektoncd/pipeline#3985

@afrittoli Would appreciate your help with creating the missing branches :pray:

**Comment by afrittoli** [comment]
> * release-v0.

I created all the missing branches - release-v0.24.x was already there since we had a minor release in the meantime.

**Comment by eliasnorrby** [comment]
Awesome, thanks! I'll try to open the remaining PRs later today.
