### ISSUE TITLE
Installation section

### ISSUE THREAD

**Issue by geriom** [tektoncd/website#346]
### Feature request

Create an installation section to cover installation for different components and different vendors. As outlined in the [roadmap](https://github.com/tektoncd/website/blob/main/roadmap.md#updates-to-documentation-structure).

### Use case

To make the installation instructions more discoverable, create a section with installation tutorials for every case.

### Tasks to refactor installation section.

After discussing in the WG, this is a list of tasks to have an installation section that pulls the instructions from component each repo.

- [x] [Modify sync script to comment out frontmatter](https://github.com/tektoncd/website/pull/429). This will allow us to import the contents of the the files into another.
- [x] Add local installation to website repo.
- [x] Update installation tutorial in the rest of the repos.
   -  [Triggers](https://github.com/tektoncd/triggers/pull/1436)
- [x] [Enable shortcode rendering in imported files](https://github.com/google/docsy/pull/1203).
- [x] Update docsy release to include changes from previous point.
- [x] Publish all installation files in their own section.

**Comment by geriom** [comment]
I have currently a draft to address this issue #377, but may require bigger updates to avoid content drift.

/lifecycle frozen
